version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:1.25.0 # Use a recent version
    ports:
      - "8080:8080" # HTTP
      - "50051:50051" # gRPC
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none' # We'll provide our own vectors
      ENABLE_MODULES: '' # No specific modules needed if we provide vectors
    restart: on-failure:0